"""One-time authoring snapshot; do not rerun over later source refinements."""
from authoring_helpers import *
DIR='liao-song-xia-jin-yuan';REG=f'content/assets/{DIR}-assets.json';N='NMC-LIAO-SONG-XIA-JIN-YUAN';M='NEAC-MONGOL-YUAN-HISTORY';G='SCIO-YUAN-PROVINCES';B='BJ-YUAN-DADU-WALL';L='CASS-YUAN-LOCAL-OFFICIALS';P='MET-YUAN-PAIZA';O='MET-OPEN-ACCESS';R='HEBEI-YUAN-RELAY';Q='GANSU-YUAN-PAIZA-RESEARCH';U='UNESCO-SONG-YUAN-QUANZHOU'
for id,inst,title,url,use in [(B,'北京市人民政府','元大都城垣遗址公园','https://www.beijing.gov.cn/renwen/rwzyd/qgzdwwbhdw/yddcqyz/202210/t20221031_2848744.html','公园建立在元大都土城遗址上；遗址现状与元朝都城的关系，不以照片重建古城'),(L,'中国社会科学院法学研究所；李治安','元代县官研究','https://iolaw.cssn.cn/gdfls/200409/t20040930_4593101.shtml','元代地方机构层次、县级官府亲临民事与办理地方事务；虚构桥梁故事只是教学举例'),(P,'The Metropolitan Museum of Art','Safe Conduct Pass (Paiza) with Inscription in Phakpa Script','https://www.metmuseum.org/art/collection/search/39624','中国元代13世纪晚期八思巴文铁牌，铁嵌银，1993.256；正反字形相反；与甘肃馆藏不是同一件'),(O,'The Metropolitan Museum of Art','Open Access at The Met','https://www.metmuseum.org/hubs/open-access','馆方标Public Domain的开放图像采用CC0；仅许可元数据'),(R,'河北省民族事务委员会','道中华：元代驿站网络与凭证','https://mw.hebei.gov.cn/system/2026/01/06/030371524.shtml','元代驿站、凭证与站户供给人力、马匹、粮草的制度背景，不把今天鸡鸣驿建筑当元代原貌'),(Q,'国务院侨务办公室转载；甘肃省博物馆李永平访谈','元朝治下东西方如何交流？','https://www.gqb.gov.cn/news/2023/0506/56998.shtml','只采用符牌作为军政、通行、传驿查验凭证的解释；甘肃圆牌与Met圆牌分开。不采用文中八思巴文字源及使用范围的过度概括')]:add_source({'id':id,'institution':inst,'title':title,'url':url,'type':'museum-open-access-policy' if id==O else 'institution-history-reference','authorityLevel':'A','factUse':use,'imageUse':'open-access' if id in [P,O] else 'reference-only'})
SR={s['id']:s for s in read('content/sources.json')['sources']}
def link(s):return {'title':SR[s]['institution']+'：'+SR[s]['title'],'url':SR[s]['url']}
def asset(id,title,path,chap,src,author,lic,licurl,caption,boundary,facts):
 d=read(REG);a={'id':id,'title':title,'localPath':f'reference-assets/{DIR}/{path}','chapterIds':[chap],'sourcePage':src,'author':author,'license':lic,'licenseUrl':licurl,'clearance':'cleared-open-license','childVisibility':'child-ok','factSourceIds':facts,'caption':caption,'boundary':boundary,'notes':boundary};d['assets']=[x for x in d['assets'] if x['id']!=id]+[a];write(REG,d);return a
id1='cn-ancient-07-04-yuan-unification';id2='cn-ancient-07-05-yuan-exchange';END='yuan-friends-reunion-v1'
wall=asset('yuan-dadu-wall-cutaway','元大都城墙遗址断面现状照片','yuan-dadu-wall-cutaway.jpg',id1,'https://commons.wikimedia.org/wiki/File:700多年前所筑城墙断面清晰可见_-_panoramio.jpg','mayanming','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0/','元代城墙遗址 · 2011年照片','照片显示遗址土墙断面与现代植被，并非元代城市原貌；层状土迹是观察点，不能从照片推出当年每段墙的高度或行政制度。摄影mayanming，CC BY-SA 3.0；原图4288×2848保留，运行图等比例缩小。',[B])
park=asset('yuan-dadu-wall-section','元大都土城遗址公园土垣照片','yuan-dadu-wall-section.jpg',id1,'https://commons.wikimedia.org/wiki/File:城墙夯土_-_Rammed-Earth_Wall_-_2012.05_-_panoramio.jpg','rheins','CC BY 3.0','https://creativecommons.org/licenses/by/3.0/','元代城墙遗址 · 2012年公园照片','照片显示公园中的土垣与树木，不是元代城墙完整原貌。摄影rheins，CC BY 3.0；原图3200×2400保留，只等比例缩制。今日公园植被不作为元代环境证据。',[B])
paizas=[]
for side in ['front','back']:
 paizas.append(asset('yuan-paiza-met-'+side,'元代八思巴文铁牌 · '+('正面' if side=='front' else '背面'),'yuan-paiza-met-'+side+'.jpg',id2,SR[P]['url'],'The Metropolitan Museum of Art（馆方开放图像）','CC0 1.0 / Met Open Access','https://creativecommons.org/publicdomain/zero/1.0/','元代13世纪晚期 · 藏品1993.256','铁地嵌银，馆方定名为通行牌。正反图为同一件Met藏品1993.256，不能串用甘肃馆藏尺寸与来源。文字可供观察，不要求孩子辨读；不能凭牌面推出具体持有人、路线或所有元代凭证的规则。馆方标Public Domain，按Met开放政策CC0使用。',[P,O]))
def ins(a,narr,src,height=330):return inspection(a['id'],a['title'],a['caption'],narr,[*[link(s) for s in src],{'title':'图像原始文件与许可','url':a['sourcePage']}],height)
def photo(a,label,period,obs,narr,src):return {'assetId':a['id'],'title':a['title'],'label':label,'period':period,'observation':obs,'narration':narr,'sourceIds':src,'sourceLinks':[*[link(s) for s in src],{'title':'图像原始文件与许可','url':a['sourcePage']}],'boundary':a['boundary']}
station='元朝完成统一以后，地方事务要分工办理，消息和人员也要借助驿站、道路与港口往来。'
# 行政分工
c=next(c for c in read(F)['chapters'] if c['id']==id1);a='yuan-local-affairs-v1'
c.update(title='元朝这么大，地方的事谁来办？',cta='去看看地方怎样办事',hook='元朝的都城大都在今天北京一带。管理这么多地方，能只靠都城里的人吗？小伙伴去看看地方的分工。',outcome='元朝完成统一后，中央与地方分工治理。行省等机构联系许多地方，基层有人核对情况、办理事务；不是一个人跑遍各地，也不是所有地区办法都相同。',anchor='忽必烈与元代中央、地方办事的人',sourceIds=[M,G,L,B],boundary='1271定国号与1279完成统一分开。元大都城墙照片为遗址现状，不是元代原貌。修桥的查验、记录是虚构教学案例，不证明所有事务都按此逐级办理。行省与路府州县等基层层次不同，中央直接管理的腹里及其他区域另有制度，不能把全国画成同一套分区。元代行省与今天省份边界职能不相同。',closingLine='中央与地方分担事情，治理还要就地办理。')
c['steps']=[step('从元大都留下的土城墙出发','这是元大都城墙留下的土迹。忽必烈1271年定国号元，1279年南宋结束、元完成统一。大都是元朝的都城，在今天北京一带。','跟着大都的土城墙，到哪个朝代？','到元朝，看看都城怎样联系地方。','宋朝更早，大都是元朝的都城。','看看这么多地方怎样分工',[M,B],kind='timeline',options=[era('元朝','1271—1368年','yuan',True),era('北宋','960—1127年','cities',False)],lead='这是元大都的城墙遗址，我们去元朝看看中央与地方。'),step('都城之外，也要有人办事','元朝管理的地域很广。中央与地方官员要分工，行省等机构联系许多地方，下面还有就近办理事情的人。我们看一个虚构的修桥故事：先了解现场，再记录情况。','地方有人了解情况，也有人办理','不是只送一张纸，还要有人做具体的事。','可以再听一遍。','找找现场和记录的两种工作',[G,L],kind='look-listen',asset=a,display='行省等机构联系各地。\n具体的事情，还要就地办理。'),step('桥边看情况，桌边记下来','居民说桥面有块石头松了。当地办事的人来到桥边核对，另一人把情况记下来。这个故事让我们看看，地方事务需要哪些工作。','谁在桥边听居民说明情况？','现场与记录，把事情慢慢弄清。','再看看他在桥边，还是在桌边。','记录还缺什么线索',[L],kind='scene-find',asset=a),step('只写桥坏了，还不够清楚','记录上只写着桥面有问题，还没说清哪一处。要了解眼前的情况，小伙伴该先找人做什么？','要弄清桥哪里坏了，先做什么？','就地查看，才能把具体情况弄清。','抄写能留下记录，眼前还需要核对现场。','把地方办事的发现连起来',[L],options=[card('到桥边核对具体位置',a,[30,80,695,515,1536,1024],True),card('在桌边继续整理文书',a,[1080,105,450,460,1536,1024],False)],asset=a),step('分担事情，也要彼此联系','查清情况后，还需要安排实际办理。元代行省等地方机构分担事务、联系中央；不同地区的办法也有差别。今天的省与它们有历史联系，却不能把边界和权力照搬过去。','地方办事，与中央相互联系','记住分工与联系，不用背下所有机构名。','可以再听一遍。','带着地方办事的发现回家',[G,L],kind='look-listen',asset=a,display='有人就地办事，也要彼此联系。\n元代行省，不等于今天的省。')]
c['steps'][0]['inspection']=ins(wall,'看土墙留下的层状痕迹。这是元大都遗址今天的一部分，树林和公园不是元代现场。中央与地方怎样办事，还要读历史资料。',[B],325);c['steps'][0]['inspection']['openAlbum']=True
scene_find(c['steps'][2],[('site','桥边核对情况的人',.06,.35,.40,.26),('record','桌边记录的人',.72,.37,.265,.19)],[('site','谁在桥边听居民说明情况？','site','他来到现场，听居民指明具体位置。','他正写记录，再找桥边的人。','再找记录情况的工作'),('record','谁正把了解的情况写下来？','record','记录帮助把地方情况联系起来。','他在桥边核对，再找拿笔的人。','记录还缺什么线索')])
c['photoAlbum']={'id':'yuan-dadu-wall','title':'大都城墙留下的土迹','label':'看看土墙与遗址公园','photos':[photo(wall,'看看土墙断面','元代遗址 · 2011年照片','找找土墙里层状的痕迹。','土墙断面留下层状痕迹。它经历了漫长的变化，不是元代城墙完整高度。',[B]),photo(park,'看看公园里的土垣','元代遗址 · 2012年照片','树木旁，土垣连成一道长坡。','这是今天公园里保留的土垣，树木和游园环境属于后来的变化。不能把它当成元代街景。',[B])]}
c['evidenceAssetIds']=[wall['id'],park['id']];c['finish']={'title':'地方的事情，要有人就地办理。','actions':['在故事图里找到现场核对与桌边记录两种工作。','家人说“地方遇到事情”，你用自己的话说说为什么还要就地了解、实际办理。'],'parent':'儿童知道中央与地方有分工即可，不要求背机构层级。修桥是虚构教学案例，不能推断每件小事都经过行省、中央；基层具体办理与省级协调不同。','sceneStepIndexes':[2,3]};presentation(c,a,END,station,1.5,1.82);c['presentation']['story']['reunionFit']='contain';save_chapter(c);update_md('content/chapters/liao-song-xia-jin-yuan-yuan-unification.md',c);add_art(REG,a,'元代地方事务：现场核对与文书记录教学插画',id1,[L,G],DIR,c['boundary'])
# 驿站
c=next(c for c in read(F)['chapters'] if c['id']==id2);a='yuan-relay-work-v1'
c.update(title='元代驿站，怎样把消息接下去？',cta='到驿站看看怎样接力',hook='送公文的人来到驿站，先要核对凭证，再准备下一程的马匹和粮草。消息要走远，谁来接这一棒？',outcome='元代驿站主要服务官方通信和运输。核对凭证、准备马匹粮草、交接文书，需要不同的人配合。道路与港口连接往来，也靠许多人的劳动。',anchor='元代使者、驿站人员与供给物资的家庭',sourceIds=[N,P,R,Q,U],boundary='Met1993.256为元代13世纪晚期铁嵌银通行牌，与甘肃同类藏品不是同一件；不编造持牌人或旅程。插画圆牌为空白学具，不是真牌复原。驿站以官方事务为主，不是所有人随意取马的旅馆；私人商路与官驿使用范围分开。洛阳桥为宋代始建、后世维修的现状对照，不能当作元代新建。',closingLine='凭证、马匹与人手，一起接住下一程。')
c['steps']=[step('从一件真正的通行牌出发','这件圆牌来自元代，牌上有八思巴文。它是一种通行凭证。小伙伴想去看看：送公文的人来到驿站，怎样按规定继续下一程？','这件通行牌，带我们去哪一朝？','去元代驿站，看看凭证与接力。','明朝在后，这件馆藏圆牌定为元代。','听听驿站为什么要准备这些',[P,R],kind='timeline',options=[era('元朝','13世纪晚期','yuan',True),era('明朝','14—17世纪','later',False)],lead='这件通行牌来自元代，我们去看驿站怎样接力。'),step('送消息，也要准备下一程','元代驿站主要为官方通信和运输服务。使者要按规定出示凭证，站里有人备马、准备粮草。消息能继续走，靠的不只是一匹马，还有供给物资和劳力的人。','核对凭证，再准备下一程','许多人的工作，托住了驿站接力。','可以再听一遍。','找找站里不同的工作',[N,R,Q],kind='look-listen',asset=a,display='先核对凭证。\n人手、马匹、粮草一起准备。'),step('柜台与马厩，谁在忙','小伙伴在这幅驿站故事图里，看到柜台边核对圆牌，也看到有人为马备草。先找核对凭证的地方，再找照料马匹的人。','哪里正在核对来人的凭证？','凭证与补给，各有工作要做。','再看看圆牌和马匹分别在哪里。','下一程准备好以后',[R,Q],kind='scene-find',asset=a),step('凭证核对好，下一程怎样接上','凭证已经核对，下一程的马也准备好了。文书还在使者身上。要让消息继续往前走，接下来该安排哪件事？','让消息继续，下一步做什么？','带好文书，换上备好的马，接着走下一程。','备草要继续做，消息还需要人接着送。','再看看水路与陆路',[R,N],options=[card('换上备好的马，带文书出发',a,[1195,120,330,460,1536,1024],True),card('继续给槽里的马备草',a,[735,160,460,350,1536,1024],False)],asset=a),step('陆路有站点，水路也有帮手','官方文书沿驿路传递，商人和货物也沿道路、桥梁与港口往来。它们的用途和规矩不完全相同。交通把不同地方连起来，也离不开沿途供给与劳动。','道路和港口，把往来连起来','把桥、站和工作的人一起记住。','可以再听一遍。','带着驿站的发现回家',[N,U,R],kind='look-listen',asset=a,display='站点、道路、桥梁与港口。\n往来离不开沿途的人。')]
c['steps'][0]['inspection']=ins(paizas[0],'看看圆牌、挂环和银色文字。这是元代八思巴文通行牌，馆藏编号1993.256。它没有告诉我们具体是哪位使者拿着走过哪里。',[P,O],330);c['steps'][0]['inspection']['openAlbum']=True
scene_find(c['steps'][2],[('credential','柜台边核对凭证的地方',.065,.32,.255,.155),('feed','为马匹准备粮草的人',.50,.31,.20,.20)],[('credential','哪里正在核对来人的凭证？','credential','圆牌和登记一起核对，再按规定办事。','这里在备草，再找柜台和圆牌。','再找为马准备粮草的人'),('feed','谁在为下一程准备马匹和粮草？','feed','有人备草照料马，接力才有条件。','那里在核对凭证，再找马槽旁的人。','看看下一程怎样开始')])
c['photoAlbum']={'id':'yuan-paiza','title':'元代通行牌的两面','label':'翻看真正通行牌的两面','photos':[photo(paizas[0],'看看正面轮廓','元代13世纪晚期','圆牌上面还有可以悬挂的环。','先看圆形的牌，再看上面的挂环。这是一种通行凭证，不是普通钱币。',[P,O]),photo(paizas[1],'看看背面的文字','元代13世纪晚期','两面的银色字形方向不同。','馆方说明，这块牌的两面字形方向相反。它们都是同一块牌的一部分，不要求小伙伴认出这些字。',[P,O])]}
c['steps'][4]['inspection']=inspection('quanzhou-luoyang-bridge-current-view','泉州洛阳桥 · 遗产现状','宋代始建 · 2020年照片 · 后世维修','长长的桥帮助连接陆路。洛阳桥宋代已经建造，后来继续使用和维修，这张是今天的样子，不是元代商人正在过桥。',[link(U),{'title':'照片作者与许可','url':'https://commons.wikimedia.org/wiki/File:Luoyang_Bridge,_Quanzhou_(20201001150149).jpg'}],325)
c['evidenceAssetIds']=[x['id'] for x in paizas]+['quanzhou-luoyang-bridge-current-view'];c['finish']={'title':'有人送，也有人准备下一程！','actions':['指柜台边的凭证，再指为马准备粮草的人，说出两种不同工作。','用一个纸卷和两个位置演示交接；每到一站，都说清是谁接、谁准备下一程。'],'parent':'重点是官方用途、使用规矩与供给劳动，不是人人拿一面牌就能任意取马。没有给博物馆牌编持有人，也不把商贸都画成官驿运输。','sceneStepIndexes':[2,3]};presentation(c,a,END,station,1.5,1.82);c['presentation']['story']['reunionFit']='contain';save_chapter(c);update_md('content/chapters/liao-song-xia-jin-yuan-yuan-exchange.md',c);add_art(REG,a,'元代驿站核对凭证、备马与粮草的故事插画',id2,[R,Q],DIR,c['boundary'])
for id in [id1,id2]:add_art(REG,END,'三位小伙伴回看元朝地方事务和驿站的插画',id,[N],DIR,'今天的旅行手册回顾图；桥、文书、马与空白圆牌是新画的学习线索，不冒充元代真实文书或符牌。完整书页以contain取景，不裁掉工作内容。')
# 同步仍由旧索引引用的配图，避免编辑层图像流回儿童入口。
p='content/step-image-overrides.json';d=read(p);cs={c['id']:c for c in read(F)['chapters'] if c['id'] in [id1,id2]}
for e in d['chapters']:
 if e['id'] in cs:
  c=cs[e['id']]
  for k in e['steps']:
   s=c['steps'][['time','beginning','journey','change','takeaway'].index(k)];e['steps'][k]=s.get('visualAssetId') or s.get('inspection',{}).get('assetId') or c['presentation']['sceneAssetId']
write(p,d)
print('Authored two Yuan chapters')
