"""One-time authoring snapshot; do not rerun over later source refinements."""
from authoring_helpers import *
import shutil
Q=pathlib.Path('docs/qa/2026-09-21-remaining-chapters'); DIR='liao-song-xia-jin-yuan'; REG=f'content/assets/{DIR}-assets.json'
for fn,src in [('song-time-study-v2','exec-9610dffb-7809-4cbf-90e1-9a5e5f790a6b.png'),('song-friends-reunion-v1','exec-12144b8a-84f3-4263-a331-10a7986e821e.png')]:shutil.copy2('/Users/chiang/.codex/generated_images/01a094d5-be50-7653-a907-8550b7e19f5a/'+src,f'reference-assets/{DIR}/{fn}.png')
N='NMC-LIAO-SONG-XIA-JIN-YUAN';D='DPM-QINGMING-SCROLL';A='CAS-ANCIENT-NAVIGATION';P='ICH-MOVABLE-TYPE-INTERVIEW';T='CAS-ANCIENT-INVENTIONS-CHRONOLOGY';S='SH-SUSHI-WATER-MELODY';POR='NPM-ZHAO-SUSHI-PORTRAIT';SHIP='QZ-SONG-SHIP-HERITAGE';B='NLC-WUJING-MING-SCAN';W='JJ-ZENG-WUJING-HISTORY'
new_sources=[(S,'上海市民政局','但愿人长久，千里共婵娟','https://mzj.sh.gov.cn/lnb-wsws/20240918/db07bfa108f94ee29e706b9bbb646c1a.html','1076年中秋密州作词、兼怀子由与下阕原文；诗歌不是家庭统计'),(POR,'台北故宫博物院','元赵孟頫行书赤壁二赋册','https://digitalarchive.npm.gov.tw/Collection/Detail/425?dep=P','1301年赵孟頫书赤壁二赋并作东坡像置于起首；不是1076年的现场'),(SHIP,'泉州市人民政府','泉州海外交通史博物馆','https://www.quanzhou.gov.cn/lyb/lysy/bwgq/201510/t20151025_176955.htm','1974年后渚港出土宋代海船残体，展陈为考古遗存；不据照片推出船上指南针'),(B,'国家图书馆馆藏；开放扫描文件页提供书目与许可','《武经总要前集》明刻本第1册，善本书号16737','https://commons.wikimedia.org/wiki/File:NLC892-411999028209-148443_武經總要前集_第1冊.pdf','图像身份与版本元数据；PDF第1页封面，第2至4页序文，馆藏水印保留'),(W,'晋江市人民政府','曾公亮和《武经总要》','https://www.jinjiang.gov.cn/yxjj/szjj/wssl/202406/t20240603_3043257.htm','1040至1044年编书、宋代军事著作与技术记录；不进入配方与制作细节')]
for id,inst,title,url,use in new_sources:add_source({'id':id,'institution':inst,'title':title,'url':url,'type':'catalog-scan-metadata' if id==B else 'institution-history-reference','authorityLevel':'B-metadata' if id==B else 'A','factUse':use,'imageUse':'open-scan' if id==B else 'reference-only'})
SR={s['id']:s for s in read('content/sources.json')['sources']}; AR={a['id']:a for a in read(REG)['assets']}
def link(s):return {'title':SR[s]['institution']+'：'+SR[s]['title'],'url':SR[s]['url']}
def ins(a,title,caption,narration,src,height=330):return inspection(a,title,caption,narration,[*[link(s) for s in src],{'title':'图像作者、原始文件与许可','url':AR[a]['sourcePage']}],height)
def register_evidence(id,title,path,author,lic,url,srcpage,facts,chapter,caption,boundary):
 a={'id':id,'title':title,'localPath':f'reference-assets/{DIR}/{path}','sourcePage':srcpage,'author':author,'license':lic,'licenseUrl':url,'clearance':'cleared-open-license','childVisibility':'child-ok','factSourceIds':facts,'chapterIds':[chapter],'caption':caption,'boundary':boundary,'notes':boundary}
 d=read(REG);d['assets']=[x for x in d['assets'] if x['id']!=id]+[a];write(REG,d);AR[id]=a
register_evidence('song-quanzhou-ship','泉州湾宋代海船遗存展览照片','song-quanzhou-ship.jpg','John Meckley（meckleychina）','CC BY 2.0','https://creativecommons.org/licenses/by/2.0/','https://commons.wikimedia.org/wiki/File:Song_Dynasty_Ancient_Ship_of_Quanzhou_Bay_20061229.jpg',[SHIP],'cn-ancient-07-07-song-compass-navigation','宋代海船残体 · 2006年参观照片','照片展示考古出土船体与现代支撑、展陈，不是宋代航行现场。摄影John Meckley，CC BY 2.0；原图1024×757保留，运行图等比例缩制。照片没有展示出土指南针，航海用针另由文献支持。')
register_evidence('wujing-ming-cover','《武经总要》后世明刻本封面书影','wujing-ming-cover.png','宋曾公亮、丁度等编；国家图书馆藏明刻本扫描','Public Domain Mark 1.0','https://creativecommons.org/publicdomain/mark/1.0/',SR[B]['url'],[B,W],'cn-ancient-07-08-song-gunpowder-records','明代刻本 · 国家图书馆藏 · PDF第1页','这是后世刻本封面，不是1044年纸本原稿，也不是火药配方所在页。扫描文件公版；整页渲染，保留馆藏水印，无AI修复或重绘。宋代成书与明代刻印分开说明。')
END='song-friends-reunion-v1'; STATION='这一站有同时存在的政权，也有繁忙的城市、不断改进的技术和寄托思念的词。每个故事都有自己的年代。'
def new(id,title,cta,hook,outcome,anchor,boundary,sources,closing):
 c=next(x for x in read(F)['chapters'] if x['id']==id);c.update(title=title,cta=cta,hook=hook,outcome=outcome,anchor=anchor,boundary=boundary,sourceIds=sources,closingLine=closing);c.pop('photoAlbum',None);return c
made=[]
def done(c,scene,filename,actions,parent,finish):
 c['finish']={'title':finish,'actions':actions,'parent':parent,'sceneStepIndexes':[2,3]};c['evidenceAssetIds']=[c['steps'][0]['inspection']['assetId']];presentation(c,scene,END,STATION,1.5,1.82);save_chapter(c);update_md(filename,c)
 add_art(REG,scene,c['title']+'故事插画',c['id'],c['sourceIds'],DIR,c['boundary']);add_art(REG,END,'宋代历史站小伙伴回看旅行册',c['id'],[N],DIR,'三位现代儿童回顾旅行手册；册上船、印刷图样与月亮为整站学习线索，不冒充古代原物或个人亲历。');made.append(c)
# 并立政权
c=new('cn-ancient-07-01-parallel-regimes','同一年，历史里住着谁？','打开两个年份看看','北宋的时候，辽和西夏也存在。后来年份变了，同一幅时间图里还有哪些政权？','1111年看辽、北宋、西夏；1160年看金、南宋、西夏。历史中既有先后，也有同时存在的政权，它们之间有冲突，也有往来。','北宋、南宋与并立的辽、西夏、金','年份卡是关系学具，不画疆界或现代国家。三个图标同样大小不代表疆域大小；两个年份不是唯一并立组合，1111年还有其他政权。画卷为北宋艺术材料，不能当作1111年当天记录。',[N,'NEAC-LIAO-SONG-XIA-JIN-CHINA',D],'看清年份，也看见同时存在的历史。')
a='song-time-study-v2'
c['steps']=[step('先从北宋的画走进去','这是真正的北宋《清明上河图》局部，画里有船、有桥。这一时期还有别的政权，我们一起打开两个年份看看。','张择端的画带我们来到哪个时期？','来到北宋，再看同一年还有谁。','南宋在后，这幅画描绘北宋生活。','打开同一年的时间窗',[D,N],kind='timeline',options=[era('北宋','960—1127年','cities',True),era('南宋','1127—1279年','cities',False)],lead='张择端画的是北宋。那时还有其他政权。'),step('一条时间河，也有同时存在的人家','1111年，辽、北宋和西夏同时存在。它们不是一国结束、下一国才出现。彼此有交战、和议和往来；不同地方的人，也在相互影响。','同一年里，可以有不同政权','先记住同时存在，再看年份的变化。','可以再听一遍。','把年份往后看',[N,'NEAC-LIAO-SONG-XIA-JIN-CHINA'],kind='look-listen',asset=a,display='1111年：辽、北宋、西夏。\n它们在同一年里存在。'),step('年份变了，组合也会变','先听1111年的名字：辽、北宋、西夏。把年份往后拨到1160年，再听听谁变了、谁还在。','把时间从1111年往后看','1160年，换成金、南宋与西夏。','可以再看看。','给1160年选一组卡',[N,'NEAC-LIAO-SONG-XIA-JIN-CHINA'],kind='history-lab'),step('把同一年的伙伴放在一起','我们现在停在1160年。北宋已经结束，南方是南宋；北方有金，西北还有西夏。听一听两组卡的名字。','1160年，应该选哪一组？','这一年看金、南宋和西夏。','那一组属于更早的1111年。','看看它们之间的往来',[N,'NEAC-LIAO-SONG-XIA-JIN-CHINA'],options=[{'label':'金、南宋、西夏','correct':True,'visual':visual('金','南宋','西夏'),'objectView':{'kind':'polity-panel','windowIndex':1}},{'label':'辽、北宋、西夏','correct':False,'visual':visual('辽','北宋','西夏'),'objectView':{'kind':'polity-panel','windowIndex':0}}],asset=a),step('同时存在，也彼此影响','小伙伴把同一年的卡片并排放好。不同政权之间既有冲突，也有人来往、货物交换和文化交流。以后再看历史图，先听清它是哪一年。','历史既有先后，也有同时','知道是哪一年，才不会把不同年代混在一起。','可以再听一遍。','带着两个年份的发现回家',[N,'NEAC-LIAO-SONG-XIA-JIN-CHINA'],kind='look-listen',asset=a,display='先看哪一年。\n再看谁和谁同时存在。')]
c['steps'][0]['inspection']=ins('qingming-scroll-rainbow-bridge-detail','《清明上河图》局部 · 北宋','张择端作品 · 原作局部影像','画里有桥、船与不同工作的人。这是北宋绘画，不是某一年拍下的照片；政权并立要由历史记录来核对。',[D],315)
c['steps'][2]['interaction']['lab']={'kind':'polities','stages':[{'label':'看看1160年','narration':'到了1160年，这一组是金、南宋和西夏。西夏在两个年份里都能看到。'}]}
done(c,a,'content/chapters/liao-song-xia-jin-yuan-parallel-regimes.md',['家人说1111年，你听着说出辽、北宋、西夏，也可以请家人代读。','再说1160年的金、南宋、西夏，指出两个年份里都出现的西夏。'],'不要求背年表。能表达“同一年有几家，往后组合会变”即可；这些政权不是宋的下属，也不能直接套现代国家关系。','同一年，也能看见几段历史！')
# 城市
c=new('cn-ancient-07-02-song-economy-cities','清明上河图里，谁让城市忙起来？','去桥边找找忙碌的人','长卷里的桥上桥下都很热闹。船工、搬运者和店里的人，怎样把水路与街市接起来？','北宋画家张择端画下汴京的城市生活。河船、桥梁、搬运和买卖彼此联系，热闹背后有许多人的劳动。','张择端与汴京街市里的人们','原作局部与现代港口教学插画分开。画中的漕船不能替所有货物编运输路线；图画是画家选择的场景，不代表所有家庭同样富足。新场景不是《清明上河图》的复制。',[D,N],'桥上桥下，许多工作连起城市。')
a='song-city-work-v1';true='qingming-scroll-rainbow-bridge-detail'
c['steps']=[step('一幅真正的北宋长卷','张择端画下汴京的街市。我们先看真正的画卷局部：河边有船，桥上有人。这次去北宋看看。','这幅画里的故事在哪个时期？','去北宋，看看桥上桥下。','唐朝更早，这幅作品来自北宋。','听听画里的城市',[D],kind='timeline',options=[era('北宋','960—1127年','cities',True),era('唐朝','618—907年','tang',False)],lead='这是北宋张择端的《清明上河图》。'),step('河流把货物带到城市','画中的汴河是运输的水路。桥下船工忙着过桥，桥上行人和商贩往来。有人运货、有人搬运、有人买卖，城市生活靠不同工作接在一起。','先看看桥下，再看看桥上','找找画里不同的路和工作。','可以再听一遍。','在真画里找一找',[D,N],kind='look-listen',asset=true,display='河里有船。\n桥上有人，街边有买卖。'),step('从真画里找水路和桥','跟小伙伴看看这幅真画：河船走水路，行人可以从桥上过去。先找船，再找过河的桥。','找到在河里运输的船','桥上桥下，各有通行的办法。','再看看河面和桥面。','货到岸边，还要谁帮忙',[D],kind='scene-find',asset=true),step('从船上到街边，还要接一程','这幅新画演一段搬运故事。货物到了岸边，接下来要送进街边。船工和搬运者各有工作，小伙伴该找谁接这一程？','把岸边货物送到街边，找谁？','搬运的人接上这一程，水路和街市连起来。','船工照料河里的船，再找背着货的人。','再回看长卷里的生活',[D,N],options=[card('找背货的搬运者',a,[1040,150,375,370,1536,1024],True),card('找撑船的船工',a,[135,160,325,460,1536,1024],False)],asset=a),step('热闹里，也看见不同生活','长卷让我们看见许多人的工作。画家只画了他选择的场景，不能说明所有人过得一样。看见热闹，也别忘了撑船、搬运和做东西的人。','把人的工作也看进画里','城市的日常，是许多劳动接起来的。','可以再听一遍。','带着城市的发现回家',[D,N],kind='look-listen',asset=true,display='看热闹，也看劳动。\n一幅画，不等于所有人的生活。')]
c['steps'][0]['inspection']=ins(true,'张择端《清明上河图》虹桥局部','北宋原作局部 · 不是整卷','先看看弯弯的桥，再看看桥边的船。画家画出了不同的工作；这是绘画，不是当天的照片。',[D],320)
c['steps'][1]['inspection']={**c['steps'][0]['inspection'],'displayHeight':335};c['steps'][4]['inspection']={**c['steps'][0]['inspection'],'displayHeight':335}
scene_find(c['steps'][2],[('boat','河里的船',.68,.16,.29,.28),('bridge','行人走的桥',.37,.25,.17,.43)],[('boat','找到在河里运输的船','boat','船把货物沿水路带来。','这里是桥面，再看看河里的船。','再找行人过河的路'),('bridge','行人要过河，可以走哪里？','bridge','桥把河两边的通行连起来。','这是水里的船，再找桥面。','看看岸边接下来的工作')],label='文物图像',ratio=2)
done(c,a,'content/chapters/liao-song-xia-jin-yuan-song-economy-cities.md',['在真画里指出船和桥，分别说谁从这里经过。','家人说“货到岸边了”，你指搬运者怎样把它接到街市。'],'交通和劳动服务城市商业；不把画中每个人身份都猜定，不用一幅画推出所有家庭富足。','城市的热闹，靠大家一起忙！')
# 印刷
c=new('cn-ancient-07-03-song-inventions','毕昇的活字，怎样换一句话？','拆一块，换一块，再印一页','一整页刻在一块版上，和一块一个字有什么不同？跟小伙伴试试拆换、重排，再看看印到纸上的变化。','北宋毕昇探索泥活字，沈括把方法记在《梦溪笔谈》里。分开的字块可以拆换和重排；后人继续改进，雕版也长期使用。','毕昇、沈括与后来的印刷工匠','照片为北京印刷博物馆的木活字展示，不是毕昇泥活字原套。代码用三个简单字演示单块替换、反字到正字；不复原材料、加热、配方和完整传统工序。现代体验图不是宋代现场，活字没有立刻替代雕版。',[P,'CAS-MOVABLE-TYPE-HISTORY','CAS-PRINT-WORKSHOP-2025'],'一个个字块，拆开以后还能重排。')
a='song-print-work-v1'
c['steps']=[step('从后来的字块，追到北宋的办法','这张照片是现代博物馆展示的木活字。它们一块一块分开。更早的北宋，毕昇探索的是泥活字，沈括把方法记在书里。','毕昇探索泥活字，在哪个时期？','到北宋，看看一块一个字的办法。','明朝在后，毕昇生活在北宋。','看看字块怎样分开',[P,'CAS-MOVABLE-TYPE-HISTORY'],kind='timeline',options=[era('北宋','11世纪','cities',True),era('明朝','14世纪以后','later',False)],lead='毕昇生活在北宋，探索泥活字。照片是后来木活字的展示。'),step('一块一个字，先排成一页','雕版把一页刻在整块版上；活字把字做成分开的小块。小伙伴来到今天的体验工坊，看到字块排成一页，用完还可以拆开，再排别的内容。','分开的小字块，可以重新安排','接下来只换中间一块，两旁的留下。','可以再听一遍。','动手换中间的字',[P,'CAS-PRINT-WORKSHOP-2025'],kind='look-listen',asset=a,display='一块一个字。\n拆下来，再排成新的一页。'),step('这次只换中间一块','我们用日、月、山三个简单字作学具。中间要换成月字，两旁不动。取出旧块，放入新块，最后看看纸上的印迹。','只换中间一块，试着印一页','换了中间字，两旁仍在原处，印出来了。','再看看中间的空位。','下一页还能怎样排',[P,'CAS-PRINT-WORKSHOP-2025'],kind='history-lab'),step('另一页，还想换内容','下一页要印不同的话。哪种版能把一个个字拿出来重新排？看看是分开的小块，还是连成一整页的版。','哪种版能拆开字块，重新排列？','分开的字块可以拆下，再排到别处。','整块雕版连成一页，不能这样逐块重排。','听听方法怎样传下来',[P],options=[{'label':'一块一个字，拆开重排','correct':True,'visual':visual('分开字块','重新排列'),'objectView':{'kind':'printing-panel','connected':False}},{'label':'一整块版，保留整页','correct':False,'visual':visual('整页雕版'),'objectView':{'kind':'printing-panel','connected':True}}],asset=a),step('方法被记下，又被继续改进','毕昇的原套泥活字没有保存到今天。我们通过沈括的记载认识他的办法，也能看后来人的活字。印刷有不同方法，工匠会根据需要选择，雕版也一直被使用。','前人留下办法，后人接着探索','看真材料，也记得它们各自的时代。','可以再听一遍。','带着活字的发现回家',[P,'CAS-MOVABLE-TYPE-HISTORY'],kind='look-listen',asset=a,display='沈括把办法记下来。\n后人继续探索，雕版也长期使用。')]
c['steps'][0]['inspection']=ins('wooden-movable-type-museum-display','木活字展示 · 后来的材料','现代博物馆陈列 · 不是毕昇原物','看一块块分开的木活字。这张是真实展览照片，但它们不是毕昇当年的泥活字，只帮助我们比较分字排列的办法。',[P,'CAS-MOVABLE-TYPE-HISTORY'],320)
c['steps'][2]['interaction']['lab']={'kind':'printing','stages':[{'label':'拿出中间那块','narration':'中间空出来了，两旁的字块留在原处。'},{'label':'放入月字块','narration':'月字换进来了，只动了中间这一块。'},{'label':'印到纸上看看','narration':'版上是反字，纸上印成正字。这页变了，字块以后还可以再用。'}]}
done(c,a,'content/chapters/liao-song-xia-jin-yuan-song-inventions.md',['用三张纸片代替字块，只换中间一张，其他两张保留。','请家人换一句新口令，再把纸片重新排列；说说为什么要分成小块。'],'不要求识字或刻字，日月山可由成人读。学具省略真实制版和固定等工序；不将雕版说成无用或落后。','换一块，真的印出新的一页！')
# 指南针
c=new('cn-ancient-07-07-song-compass-navigation','宋代海船，怎样在阴天辨方向？','上船看看方向与风浪','天空被云遮住，海上的船员怎样辨方向？看看指南针能告诉什么，再找找船上其他人的工作。','宋代航海文献记载用指南针辨方向。磁针给南北线索，船员还要看风浪、海岸和水深；远航需要工具、经验与合作。','宋代船员与记录航海的作者','泉州古船照片是考古船体与现代展陈，没有展示指南针出土；用针的事实由文献支持。船上插画是教学情境，不复原特定古船。方向模型固定红端指南，省略磁偏角、摇晃和磁干扰，不能作真实航海教程。',[A,SHIP,N],'针给方向，航海还要大家观察。')
a='song-compass-crew-v1'
c['steps']=[step('从一艘真古船出发','这张照片展示泉州湾出土的宋代海船残体。宋代文献还记下船员用指南针辨方向的办法。今天跟小伙伴去看看。','这次海船故事，先到哪个朝代？','到宋代，看看海上的方向线索。','隋朝更早，这次看宋代航海记录。','听听阴天里的问题',[SHIP,A],kind='timeline',options=[era('宋朝','10—13世纪','cities',True),era('隋朝','6—7世纪','sui',False)],lead='这是宋代海船的遗存，我们去宋代看看怎样辨方向。'),step('太阳和星星被云遮住了','古人会看太阳和星星辨方向。宋代的航海记录还说，阴天可以看指南针。针稳定后给南北线索，船员就多了一种判断办法。','阴天里，磁针也能给方向线索','我们转一转学具里的船，看看针。','可以再听一遍。','转动小船，观察磁针',[A],kind='look-listen',asset=a,display='看不见太阳、星星时，\n磁针能补充方向线索。'),step('船转了，针会跟着船头转吗','这是方向学具，红端表示南。让小船转一转，观察磁针与南北方向。它帮助理解原理，不是古船上的原物。','转动船身，看磁针指向哪里','船头转了，磁针仍给南北方向。','可以再观察。','船上还要看什么',[A],kind='history-lab'),step('方向之外，还有风与水深','知道方向以后，还要看看风怎样吹、水有多深。这幅故事画里，船员分工观察，不能只盯着一根针。','谁在看风把布条吹向哪边？','不同的观察，要一起用。','再看看他手里的东西。','听听远航需要的帮手',[A],kind='scene-find',asset=a),step('一根针，接上许多人的经验','指南针把方向线索带到海上，船员还要结合太阳、星星、海岸、风浪和水深。工具帮人判断，航行仍要靠人们观察、商量和照料船只。','工具与人的经验一起工作','方向找到了，也别忘了风与海。','可以再听一遍。','带着航海的发现回家',[A,N],kind='look-listen',asset=a,display='磁针辨方向。\n观察风与海，靠船员合作。')]
c['steps'][0]['inspection']=ins('song-quanzhou-ship','泉州湾宋代海船遗存','宋代古船残体 · 2006年展览照片','看看留下来的船底和一格格船舱。这是出土古船的展陈，不是宋代正在航行的照片。指南针的使用，还要读航海文献。',[SHIP,A],325)
c['steps'][2]['interaction']['lab']={'kind':'compass','stages':[{'label':'让小船转一下','narration':'船头转到一边，红色针端仍指向南。'},{'label':'再把船转一下','narration':'船头又转了，磁针仍指着南北；它给方向，不替人开船。'}]}
scene_find(c['steps'][3],[('wind','看风中旗条的人',.39,.045,.24,.40),('depth','放绳测水深的人',.74,.33,.24,.37),('needle','查看磁针的人',.025,.53,.25,.24)],[('wind','谁在看风把布条吹向哪边？','wind','风把布条吹动，人要留意风向。','他在看别的线索，再找抬头看布条的人。','再找测量水深的人'),('depth','想知道水有多深，谁在帮忙？','depth','他在放下测深绳，检查水深。','磁针和风向不告诉水深，再看看绳子。','把船员的办法连起来')])
done(c,a,'content/chapters/song-compass-navigation.md',['用手指当磁针一直指向同一边，让家人把纸船转个方向。','再指图里的看风和测深工作，说说磁针还不能告诉我们什么。'],'只作桌面方向体验，不用真实针具，不把模型当航海导航。1099—1102是文献叙述的海船使用时期，不是《萍洲可谈》成书日期。','方向要辨，风与海也要看！')
p=pathlib.Path('content/chapters/song-compass-navigation.md');t=p.read_text().replace('1099—1102 年间成书的文献记录海船在阴晦天气看指南针','宋代朱彧所述1099—1102年间海船活动的文献记录提到阴晦天气看指南针');p.write_text(t)
# 火药文献
c=new('cn-ancient-07-08-song-gunpowder-records','古书怎样留下火药的历史？','去古书里找时间线索','火药经过长期探索，宋代已经用到军事。一本古书把知识记下来，后人又怎样把它传到今天？','火药知识经过长期探索，北宋1044年编成的《武经总要》留下军事技术记录。后来的刻印与保存，让今天还能研究这些知识的历史。','曾公亮等编书者与保存古籍的人们','儿童看的是明刻本封面，不是1044年原纸或配方所在页。新插画是今天的图书馆教学场景，图中书和笔记不冒充真实古籍。学习技术积累、军事用途和文献传承，不展示配比、制作、点火或武器操作。',[W,T,B],'探索、记录与保存，把知识带到今天。')
a='song-books-museum-v1'
c['steps']=[step('宋代编的书，后来人继续保存','《武经总要》在北宋1044年编成。照片是后来明代刻本的封面，时间比编书晚得多。先到北宋，看看这本书为何留下记录。','《武经总要》最初编成在哪一朝？','先到北宋，再看书怎样传下来。','明代刻本在后，最初编书在北宋。','听听为什么把知识写进书',[W,B],kind='timeline',options=[era('北宋','1044年','cities',True),era('明朝','14—17世纪','later',False)],lead='这本书最初在北宋编成。照片是后来留下的明代刻本。'),step('已经有人探索，也有人记下来','火药知识经过长期探索，宋代已经用于军事。曾公亮等人编写《武经总要》，整理当时的知识。书不是发明突然开始的那一天，而是留下记录的一条线索。','古书把当时的知识留下来','前面的探索和后来的记录要分开。','可以再听一遍。','到今天的图书馆找线索',[W,T],kind='look-listen',asset=a,display='先有长期探索。\n北宋编书，记录军事技术。'),step('旧书和今天的笔记，谁留下什么','小伙伴在今天的图书馆看旧书。旁边的人正在做研究笔记：旧书保留以前的文字，今天的笔记记录现在的理解。两种记录不是同一时代。','哪本书是从以前保存下来的？','旧书与今天的研究，各有时间。','再看看展柜与正在书写的地方。','比一比成书与刻印的时间',[W,B],kind='scene-find',asset=a),step('宋代编书，明代又刻印','这本书最初在北宋编成，我们看到的封面却来自明代刻本。小伙伴把两张时间卡排在心里：先有书的内容，后人再刻印流传。','北宋编书和明代刻印，哪个先？','先在北宋编书，后来还有新的刻本。','明代刻印在后，不能改成宋代原纸。','听听一本书的接力',[W,B],options=[era('北宋编成','1044年','cities',True,'calendar'),era('明代刻印','1368—1644年间','later',False,'calendar')],kind='timeline'),step('不同时间的人，把知识接下去','古人探索和记录，后人刻印、保存，今天的人再研究。火药后来也用于不同场合；了解用途，要看对应时代的材料。我们用古书和时间线，认识技术怎样积累。','一项技术，有很长的历史','留下记录，后来的人才能继续认识历史。','可以再听一遍。','带着古书的发现回家',[W,T,B],kind='look-listen',asset=a,display='探索 → 记录 → 刻印保存。\n后来的研究，仍要核对年代。')]
c['steps'][0]['inspection']=ins('wujing-ming-cover','《武经总要》· 后世刻本封面','明代刻本 · 国图藏扫描第1页','这张是真正旧书封面的书影。书的内容在北宋编成，这一本却是明代刻印流传的。圆形水印来自现代馆藏扫描，不是宋代印记。',[B,W],335)
scene_find(c['steps'][2],[('old','展柜里的旧书',.055,.555,.325,.23),('note','今天做研究笔记的地方',.62,.64,.34,.15)],[('old','哪本书是从以前保存下来的？','old','展柜里的旧书，保留以前流传的内容。','这是今天的笔记，再看看展柜。','再找今天的研究记录'),('note','今天的人正在哪里写研究笔记？','note','这份笔记记下今天的观察与理解。','旧书是以前留下的，再找正在写字的手。','把两个时间点分清楚')])
done(c,a,'content/chapters/song-gunpowder-records.md',['用三个纸片或三个位置表示探索、编书、后世保存，请家人读出来。','指旧书，再指今天的笔记，说出它们为什么不是同一时期的记录。'],'本章认识技术史而非安全口号；明确火药早于1044编书、宋代军事应用与后世版本。不会以儿童实验重做配制或点火，不以战争胜负得分。','古书把以前的知识带到今天！')
# 苏轼
c=new('cn-ancient-07-06-su-shi-moon','跟苏轼望月，给远方一份祝愿','去听月亮里的祝愿','中秋的月亮很圆，苏轼却和弟弟相隔两地。他把怎样的牵挂，写进《水调歌头》？','1076年中秋，北宋苏轼写《水调歌头》，也思念弟弟苏辙。他借明月寄托祝愿：虽然相隔千里，仍愿亲人平安。','苏轼与弟弟苏辙','《水调歌头》为苏轼词作，主线标明节选，不把诗意当作现场记录。首步为元代赵孟頫1301年所作苏轼像，画中不是作词当夜。两处窗景为文学想象，不标作密州、齐州的真实建筑或苏氏兄弟肖像；三位儿童是今天的读者。',[S,POR,'CCDI-SUSHI-WATER-MELODY'],'相隔很远，也能把牵挂放在同一轮月亮里。')
a='song-moon-wishes-v1'
c['steps']=[step('画里的人，词里的年代','这是后人画的苏轼像。苏轼生活在北宋，1076年中秋写下《水调歌头》，也想到远方的弟弟苏辙。画像是更晚的元代作品。','苏轼写这首词，应该在哪一站？','到北宋，听他写给远方的牵挂。','元代画像更晚，作词的人生活在北宋。','轻轻听这段词',[S,POR],kind='timeline',options=[era('北宋','1076年','cities',True),era('元朝','1301年画像','yuan',False)],lead='苏轼生活在北宋。这张画像是后来的元代作品。'),step('听听《水调歌头》里的祝愿','苏轼在中秋想到远方的弟弟。这是《水调歌头》节选：人有悲欢离合，月有阴晴圆缺，此事古难全。但愿人长久，千里共婵娟。','《水调歌头》· 节选','听到哪一句，就慢慢想一想。','可以再听一遍。','看看词把祝愿托给什么',[S],kind='look-listen',asset=a,display='人有悲欢离合，月有阴晴圆缺，\n此事古难全。\n但愿人长久，千里共婵娟。'),step('词把牵挂托给了什么','人可以写信问候，也可以在词里寄托祝愿。苏轼写“千里共婵娟”，这里的婵娟指明月。小伙伴从这幅想象画里找找。','这句词把远方的祝愿托给什么？','他借明月，表达对远方亲人的牵挂。','信也能问候，这句词借的是明月。','再看看相隔两地的人',[S],options=[card('同一轮明月',a,[750,42,145,148,1536,1024],True),card('桌上的书信',a,[170,374,210,74,1536,1024],False)],asset=a),step('人分在两处，牵挂还能相连','图里两处窗边的人各在一地，下面的小伙伴却站在一起。苏轼想念弟弟时，也是在相隔两地的处境里。看看这幅画怎样表达远方。','哪组人各在一处，却想着彼此？','两处窗景表达相隔，明月寄托牵挂。','小伙伴站在一起，再找两处窗边的人。','把自己的祝愿轻轻说出来',[S],kind='scene-find',asset=a),step('把祝愿带给你牵挂的人','“但愿人长久，千里共婵娟。”希望亲人平安，虽然相隔很远，也能共赏明月。你也可以想一个牵挂的人，说一句自己的祝愿，不用背出整首词。','轻轻望月，想一个牵挂的人','你的祝愿，可以用自己的话说。','可以再听一遍。','带着祝愿回家',[S],kind='look-listen',asset=a,display='但愿人长久，千里共婵娟。\n也给你牵挂的人，一份祝愿。')]
c['steps'][0]['inspection']=ins('su-shi-yuan-portrait-artwork','苏轼像 · 元代赵孟頫绘','1301年后世画像 · 人物是北宋苏轼','这张画画的是苏轼，但画家赵孟頫生活在更晚的元代。画像让后人纪念苏轼，不能当作他写词那一夜的照片。',[POR,S],350)
scene_find(c['steps'][3],[('apart','两处窗边的亲人',.025,.04,.95,.40),('together','站在一起的小伙伴',.13,.565,.65,.40)],[('apart','哪组人各在一处，却想着彼此？','apart','两处窗景表达相隔，明月寄托牵挂。','小伙伴站在一起，再找两处窗边的人。','听听这句祝愿')])
done(c,a,'content/chapters/song-su-shi-moon.md',['听“千里共婵娟”，分别指画里两处窗边的人，再指月亮。','想一个牵挂的人，用自己的话说一句祝愿，也可以请家人代说。'],'不把诗词变成背诵竞赛，不规定孩子一定悲伤或必须思念某个人。明确节选和文学想象；李白思乡与苏轼兼怀子由各有作品语境。','给远方的人，一份温柔的祝愿。')
# 修正新来源关联，保留旧素材但停止作当前儿童证据。
d=read(REG)
for a in d['assets']:
 if a['id']=='su-shi-yuan-portrait-artwork':a['factSourceIds']=list(dict.fromkeys(a['factSourceIds']+[POR]));a['notes']+=' 台北故宫故书000155、1301年册首画像身份已核对。'
 if a['id'] in ['liao-song-xixia-jin-two-times-child-map','wujing-zongyao-fire-arrow-diagram','gunpowder-record-safety-child-illustration']:a['childVisibility']='editor-only';a['notes']+=' 2026-09-21当前章改用代码关系图或明确版本的封面及新教学场景；旧图仅存档，不用于本轮儿童观察。'
write(REG,d)
(Q/'song-design.md').write_text('# 宋辽夏金六章对应关系\n\n本轮目标1280×720；固定五步与完成状态不变。\n\n| 章节 | 核心史实 | 真实依据 | 主要参与动作 |\n| --- | --- | --- | --- |\n'+''.join('| '+c['title']+' | '+c['outcome']+' | '+c['steps'][0]['inspection']['title']+'；文献：'+', '.join(c['sourceIds'])+' | '+'、'.join(s['interaction']['kind'] for s in c['steps'])+' |\n' for c in made)+'\n真图与新画分开；阶段模型由共享状态控制，印刷完成才前进、船转不改变磁针方向、年份变化不把政权混在一起。最后阅读页保留完整短故事与具体亲子动作。\n')
print('Authored',len(made),'Song chapters')
